[package]
name = 'DAT3CoinBoot'
version = '0.0.5'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"


[addresses]
dat3 = "0xc9f23ee5d4a4fe4dc30d81c900a8f2ecf9e5cca363e6a5bf20d8e6cf740b6197"
dat3_admin = "0xfeca5fb44de9a008a573e8a1fba809f4bd0150cd4804646f0b5ca23c2e410ca3"