[package]
name = 'DAT3CoinBoot'
version = '0.0.2'
upgrade_policy = "compatible"

[addresses]
dat3 = "0xf4fda1c5c66c5d233e3bf6f65d4f7ff9a72b0b7f3222c80fe8e4a68ac1ff3ebd"
dat3_admin = "0xd30a63cec1a5fea7fddb2abb744cb4cd0fdd723a9d290f599cbe6774ec455db7"
[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"
#[addresses]
#std="0x1"
#dat3 = "0xdc93ea6bd71ba363df305d0651e242d47a113a655af28bff1f009ebc68b4ff21"
#dat3_admin = "0xdc93ea6bd71ba363df305d0651e242d47a113a655af28bff1f009ebc68b4ff21"
#[dependencies.AptosFramework]
#git = "https://github.com/aptos-labs/aptos-core.git"
#subdir = "aptos-move/framework/aptos-framework"
## rev = "563e2abff8fa997aec81abe48772af8a20731f76"
#rev = "main"