[package]
name = 'DAT3CoinBoot'
version = '0.0.1'
upgrade_policy = "compatible"

[addresses]
dat3 = "0x4e952f93a49ad67364ad433f08ff6300b5f2d8fcb7faf0c379683d9bac3b6742"
dat3_admin = "0x4e952f93a49ad67364ad433f08ff6300b5f2d8fcb7faf0c379683d9bac3b6742"

[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"

[dev-dependencies.MoveStdlib]
local = "../../aptos-core-1.0.4/aptos-move/framework/move-stdlib"

[dev-dependencies.AptosStdlib]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-stdlib"