[package]
name = 'DAT3Pool'
version = '0.0.1'
upgrade_policy = "compatible"
[dependencies]
# # https://github.com/aptos-labs/aptos-core.git
AptosFramework = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-token" }
DAT3CoinBoot = { local = "../dat3coinboot" }
veDAT3Coin = { local = "../veDAT3Coin" }
[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
dat3 = "0xed1414caa93cbd5e9df64b1319417a6592559c8f9389a166c76c3a53dd23a994"
dat3_admin = "0x6f1396cd716ba8d1263f96cb24dd8a41770bce2ec78afe5385956754fcd9e6dc"