[package]
name = 'DAT3Poll'
version = '1.0.0'
[dependencies]
# # https://github.com/aptos-labs/aptos-core.git
AptosFramework = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework" }
[addresses]
sdt = "0x1"
publisher = "0xf2b1"