[package]
name = 'DAT3Pool'
version = '0.0.1'
upgrade_policy = "compatible"
[dependencies]
# # https://github.com/aptos-labs/aptos-core.git
AptosFramework = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework" }
AptosToken = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-token" }
DAT3CoinBoot = { local = "../dat3coinboot" }
[addresses]
sdt = "0x1"
dat3 = "0x7d8320a497c20c1569cb6fecd7cc564f873de6316c462748a2b9c935e847384b"
dat3_admin = "0x82ab0ed20d1c2935be9141ffed86eb3409d0c46459dc9131d26fbf89997db565"