[package]
name = 'veDAT3Coin'
version = '0.0.1'
upgrade_policy = "compatible"

[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"

[addresses]
vedat3 = "0x7f42cc5bed4aa5a2660b2d06b41aa078963c62f4733fae686a18a6bef31b9270"