[package]
name = 'veDAT3Coin'
version = '0.0.1'
upgrade_policy = "compatible"

[addresses]
vedat3 = "0xf793644fd85325ddcd908e87decfd0e93c605c64a8098c1aa2e9814f5558b764"
[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"