[package]
name = 'veDAT3Coin'
version = '0.0.1'
upgrade_policy = "compatible"

[addresses]
vedat3 = "0xd30a63cec1a5fea7fddb2abb744cb4cd0fdd723a9d290f599cbe6774ec455db7"
[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"