[package]
name = 'veDAT3Coin'
version = '0.0.1'
upgrade_policy = "compatible"

[addresses]
vedat3 = "0x82ab0ed20d1c2935be9141ffed86eb3409d0c46459dc9131d26fbf89997db565"

[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"