[package]
name = 'veDAT3Coin'
version = '0.0.1'
upgrade_policy = "compatible"

[addresses]
vedat3 = "0x6122e1b251c4c65ad86d16c6816fbc1cc7ea5f15a9593e5a01b0289bfd4aaa44"
[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"