[package]
name = 'veDAT3Coin'
version = '0.0.1'
upgrade_policy = "compatible"

[addresses]
vedat3 = "0xd3bc95c03d54a8da4f217c2db468613e1c1c380678cefba9dbd263a4f9d63d7f"
[dependencies.AptosFramework]
local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework"