[package]
name = 'dat3'
version = '0.0.1'
[dependencies]
#D:\work\project\move\aptos-core-1.0.4\aptos-move\framework\aptos-framework and call with the -d flag
AptosFramework = { local = "../../aptos-core-1.0.4/aptos-move/framework/aptos-framework" }
[addresses]
sdt = "0x1"
publisher = "0xf2b0"